fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: cargo
        language: rust
        files: \.rs$
        args: ["fmt", "--", "--check"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo
        language: rust
        args: ["check", "--all"]
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo
        language: rust
        files: \.rs$
        pass_filenames: false
        args: ["clippy", "--all-targets", "--all-features", "--tests", "--benches", "--", "-D", "warnings"]
      - id: cargo-test
        name: cargo test
        description: unit test for the project
        entry: cargo
        language: rust
        files: \.rs$
        pass_filenames: false
        args: ["nextest", "run", "--all-features"]
